/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace FileRegistry {
      
    export type FileMetaStruct = {owner: AddressLike, cid: string, checksum: BytesLike, size: BigNumberish, mime: string, createdAt: BigNumberish}

    export type FileMetaStructOutput = [owner: string, cid: string, checksum: string, size: bigint, mime: string, createdAt: bigint] & {owner: string, cid: string, checksum: string, size: bigint, mime: string, createdAt: bigint }
  
    }

  export interface FileRegistryInterface extends Interface {
    getFunction(nameOrSignature: "isTrustedForwarder" | "metaOf" | "ownerOf" | "register" | "updateCid" | "versionsOf"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FileRegistered" | "FileVersioned"): EventFragment;

    encodeFunctionData(functionFragment: 'isTrustedForwarder', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'metaOf', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'register', values: [BytesLike, string, BytesLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'updateCid', values: [BytesLike, string, BytesLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'versionsOf', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'isTrustedForwarder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'metaOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'register', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateCid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'versionsOf', data: BytesLike): Result;
  }

  
    export namespace FileRegisteredEvent {
      export type InputTuple = [fileId: BytesLike, owner: AddressLike, cid: string, checksum: BytesLike, size: BigNumberish, mime: string];
      export type OutputTuple = [fileId: string, owner: string, cid: string, checksum: string, size: bigint, mime: string];
      export interface OutputObject {fileId: string, owner: string, cid: string, checksum: string, size: bigint, mime: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FileVersionedEvent {
      export type InputTuple = [fileId: BytesLike, cid: string, checksum: BytesLike, size: BigNumberish, mime: string];
      export type OutputTuple = [fileId: string, cid: string, checksum: string, size: bigint, mime: string];
      export interface OutputObject {fileId: string, cid: string, checksum: string, size: bigint, mime: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FileRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): FileRegistry;
    waitForDeployment(): Promise<this>;

    interface: FileRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    isTrustedForwarder: TypedContractMethod<
      [forwarder: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    metaOf: TypedContractMethod<
      [fileId: BytesLike, ],
      [FileRegistry.FileMetaStructOutput],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [fileId: BytesLike, ],
      [string],
      'view'
    >
    

    
    register: TypedContractMethod<
      [fileId: BytesLike, cid: string, checksum: BytesLike, size: BigNumberish, mime: string, ],
      [void],
      'nonpayable'
    >
    

    
    updateCid: TypedContractMethod<
      [fileId: BytesLike, newCid: string, newChecksum: BytesLike, newSize: BigNumberish, newMime: string, ],
      [void],
      'nonpayable'
    >
    

    
    versionsOf: TypedContractMethod<
      [fileId: BytesLike, ],
      [FileRegistry.FileMetaStructOutput[]],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'isTrustedForwarder'): TypedContractMethod<
      [forwarder: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'metaOf'): TypedContractMethod<
      [fileId: BytesLike, ],
      [FileRegistry.FileMetaStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [fileId: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'register'): TypedContractMethod<
      [fileId: BytesLike, cid: string, checksum: BytesLike, size: BigNumberish, mime: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateCid'): TypedContractMethod<
      [fileId: BytesLike, newCid: string, newChecksum: BytesLike, newSize: BigNumberish, newMime: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'versionsOf'): TypedContractMethod<
      [fileId: BytesLike, ],
      [FileRegistry.FileMetaStructOutput[]],
      'view'
    >;

    getEvent(key: 'FileRegistered'): TypedContractEvent<FileRegisteredEvent.InputTuple, FileRegisteredEvent.OutputTuple, FileRegisteredEvent.OutputObject>;
getEvent(key: 'FileVersioned'): TypedContractEvent<FileVersionedEvent.InputTuple, FileVersionedEvent.OutputTuple, FileVersionedEvent.OutputObject>;

    filters: {
      
      'FileRegistered(bytes32,address,string,bytes32,uint64,string)': TypedContractEvent<FileRegisteredEvent.InputTuple, FileRegisteredEvent.OutputTuple, FileRegisteredEvent.OutputObject>;
      FileRegistered: TypedContractEvent<FileRegisteredEvent.InputTuple, FileRegisteredEvent.OutputTuple, FileRegisteredEvent.OutputObject>;
    

      'FileVersioned(bytes32,string,bytes32,uint64,string)': TypedContractEvent<FileVersionedEvent.InputTuple, FileVersionedEvent.OutputTuple, FileVersionedEvent.OutputObject>;
      FileVersioned: TypedContractEvent<FileVersionedEvent.InputTuple, FileVersionedEvent.OutputTuple, FileVersionedEvent.OutputObject>;
    
    };
  }