/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'AccessControlDFSP', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AccessControlDFSP__factory>
getContractFactory(name: 'DFSPAnchoring', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.DFSPAnchoring__factory>
getContractFactory(name: 'FileRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FileRegistry__factory>
getContractFactory(name: 'MinimalForwarder', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MinimalForwarder__factory>

  getContractAt(name: 'AccessControlDFSP', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AccessControlDFSP>
getContractAt(name: 'DFSPAnchoring', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.DFSPAnchoring>
getContractAt(name: 'FileRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FileRegistry>
getContractAt(name: 'MinimalForwarder', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MinimalForwarder>

  deployContract(name: 'AccessControlDFSP', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AccessControlDFSP>
deployContract(name: 'DFSPAnchoring', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DFSPAnchoring>
deployContract(name: 'FileRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FileRegistry>
deployContract(name: 'MinimalForwarder', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MinimalForwarder>

  deployContract(name: 'AccessControlDFSP', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AccessControlDFSP>
deployContract(name: 'DFSPAnchoring', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DFSPAnchoring>
deployContract(name: 'FileRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FileRegistry>
deployContract(name: 'MinimalForwarder', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MinimalForwarder>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  