name: dfsp-dev

# общие env-файлы (dev → local override)
x-env-files: &env_files
  env_file:
    - path: ../../deploy/.env.dev
      required: false
    - path: ../../deploy/.env.local
      required: false

services:
  web:
    image: node:${NODE_VERSION:-20}
    container_name: web
    working_dir: /app
    command: >
      sh -lc "corepack enable &&
              corepack prepare pnpm@${PNPM_VERSION:-latest} --activate &&
              pnpm install --frozen-lockfile &&
              pnpm run dev -- --host 0.0.0.0"
    environment:
      CI: "${CI:-true}"
      VITE_API_BASE: "${VITE_API_BASE:-http://localhost:${API_HOST_PORT:-8000}}"
      VITE_IPFS_PUBLIC_GATEWAY: "${VITE_IPFS_PUBLIC_GATEWAY:-http://localhost:8080}"
      VITE_CHAIN_ID: "${VITE_CHAIN_ID:-${CHAIN_ID:-31337}}"
      PNPM_STORE_DIR: /pnpm-store
    ports:
      - "${VITE_PORT:-5173}:5173"
    # ВАЖНО: /app — это volume (держит node_modules и dist),
    # а исходники точечно монтируются поверх
    volumes:
      - web_app:/app
      - web_pnpm_store:/pnpm-store
      - ./frontend_new/src:/app/src
      - ./frontend_new/public:/app/public
      - ./frontend_new/package.json:/app/package.json
      - ./frontend_new/pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./frontend_new/index.html:/app/index.html
      # если у тебя конфиг Vite называется vite.config.ts — раскомментируй строку ниже
      - ./frontend_new/vite.config.ts:/app/vite.config.ts
      # если конфиг eslint/prettier нужен внутри контейнера — добавь аналогично:
      - ./frontend_new/.eslintrc.cjs:/app/.eslintrc.cjs
      - ./frontend_new/eslint.config.js:/app/eslint.config.js
    depends_on:
      api:
        condition: service_started
    networks: [ dfsp ]
  # -------------------- backend: db/redis/migrator/api --------------------
  db:
    extends:
      file: ./backend/docker/compose.backend.yml
      service: db
    <<: *env_files
    networks: [ dfsp ]
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_HOST_PORT:-5432}:5432"
    profiles: [ "localdb" ]

  redis:
    extends:
      file: ./backend/docker/compose.backend.yml
      service: redis
    <<: *env_files
    networks: [ dfsp ]
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"

  migrator:
    extends:
      file: ./backend/docker/compose.backend.yml
      service: migrator
    <<: *env_files
    networks: [ dfsp ]
    # важное: переопределяем пути на корневые
    volumes:
      - ./backend/app:/app/app
      - ./backend/migrations:/app/migrations
      - ./backend/alembic.ini:/app/alembic.ini
    environment:
      ALEMBIC_AUTO_REVISION: "${ALEMBIC_AUTO_REVISION:-true}"
    depends_on:
      redis:
        condition: service_healthy
      # db:
      #   condition: service_healthy
    profiles: [ "migrate" ]

  api:
    extends:
      file: ./backend/docker/compose.backend.yml
      service: api
    <<: *env_files
    networks: [ dfsp ]
    ports:
      - "${API_HOST_PORT:-8000}:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/migrations:/app/migrations
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/tests:/app/tests
      - shared:/app/shared
    environment:
      API_AUTO_MIGRATE: "${API_AUTO_MIGRATE:-false}"
      ALEMBIC_AUTO_REVISION: "${ALEMBIC_AUTO_REVISION:-true}"
      CHAIN_RPC_URL: "${CHAIN_RPC_URL:-http://chain:8545}"
      CHAIN_ID: "${CHAIN_ID:-31337}"
      CONTRACTS_DEPLOYMENT_JSON: "${CONTRACTS_DEPLOYMENT_JSON:-/app/shared/deployment.localhost.json}"
      REGISTRY_CONTRACT_NAME: "${REGISTRY_CONTRACT_NAME:-FileRegistry}"
      IPFS_PUBLIC_GATEWAY_URL: "${IPFS_PUBLIC_GATEWAY_URL:-http://localhost:8080}"
      IPFS_API_URL: "${IPFS_API_URL:-http://ipfs:5001/api/v0}"
      IPFS_GATEWAY_URL: "${IPFS_GATEWAY_URL:-http://ipfs:8080}"
      CORS_ORIGINS: "${CORS_ORIGINS:-http://localhost:5173,http://127.0.0.1:5173}"
      CHAIN_TX_FROM: "${CHAIN_TX_FROM:-}"
      # New DevOps envs
      RELAYER_HIGH_QUEUE: "${RELAYER_HIGH_QUEUE:-relayer.high}"
      RELAYER_DEFAULT_QUEUE: "${RELAYER_DEFAULT_QUEUE:-relayer.default}"
      QUOTA_META_TX_PER_DAY: "${QUOTA_META_TX_PER_DAY:-50}"
      QUOTA_DOWNLOAD_BYTES_PER_DAY: "${QUOTA_DOWNLOAD_BYTES_PER_DAY:-2147483648}"
      POW_DIFFICULTY_BASE: "${POW_DIFFICULTY_BASE:-18}"
    depends_on:
      redis:
        condition: service_healthy
      #migrator:
      #  condition: service_completed_successfully
      contracts:
        condition: service_completed_successfully
      ipfs:
        condition: service_healthy

  celery-worker:
    extends:
      file: ./backend/docker/compose.backend.yml
      service: celery-worker
    <<: *env_files
    networks: [ dfsp ]
    volumes:
      - ./backend/app:/app/app
      - ./backend/migrations:/app/migrations
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/tests:/app/tests
      - shared:/app/shared
    environment:
      CHAIN_RPC_URL: "${CHAIN_RPC_URL:-http://chain:8545}"
      CHAIN_ID: "${CHAIN_ID:-31337}"
      CONTRACTS_DEPLOYMENT_JSON: "${CONTRACTS_DEPLOYMENT_JSON:-/app/shared/deployment.localhost.json}"
      REGISTRY_CONTRACT_NAME: "${REGISTRY_CONTRACT_NAME:-FileRegistry}"
      RELAYER_PRIVATE_KEY: "${RELAYER_PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}"
      RELAYER_HIGH_QUEUE: "${RELAYER_HIGH_QUEUE:-relayer.high}"
      RELAYER_DEFAULT_QUEUE: "${RELAYER_DEFAULT_QUEUE:-relayer.default}"
      RELAYER_SYNC_DEV: "${RELAYER_SYNC_DEV:-0}"
    depends_on:
      redis:
        condition: service_healthy
      contracts:
        condition: service_completed_successfully

  # ---------------------- contracts: chain/contracts/ipfs ----------------------
  chain:
    extends:
      file: ./contracts/docker/compose.dev.yml
      service: chain
    volumes:
      - contracts_app:/app
      - ./contracts/package.json:/app/package.json
      - ./contracts/package-lock.json:/app/package-lock.json
      - ./contracts/hardhat.config.ts:/app/hardhat.config.ts
      - ./contracts/tsconfig.json:/app/tsconfig.json
      - ./contracts/src:/app/src
      - ./contracts/scripts:/app/scripts
      - ./contracts/test:/app/test
      - ./contracts/deploy:/app/deploy
      - ./contracts/docker:/app/docker
      - contracts_npm_cache:/npm-cache
      - shared:/app/shared
    networks: [ dfsp ]
    ports:
      - "${CHAIN_HOST_PORT:-8545}:8545"

  contracts:
    extends:
      file: ./contracts/docker/compose.dev.yml
      service: contracts
    networks: [ dfsp ]
    volumes:
      - contracts_app:/app
      - ./contracts/package.json:/app/package.json
      - ./contracts/package-lock.json:/app/package-lock.json
      - ./contracts/hardhat.config.ts:/app/hardhat.config.ts
      - ./contracts/tsconfig.json:/app/tsconfig.json
      - ./contracts/src:/app/src
      - ./contracts/scripts:/app/scripts
      - ./contracts/test:/app/test
      - ./contracts/deploy:/app/deploy
      - ./contracts/docker:/app/docker
      - shared:/shared
      - contracts_npm_cache:/npm-cache
    depends_on:
      chain:
        condition: service_healthy
    environment:
      HARDHAT_URL: "${HARDHAT_URL:-http://chain:8545}"
      DEPLOY_OUT: "${DEPLOY_OUT:-/shared/deployment.localhost.json}"
      CHAIN_CONFIG_PATH: "${CHAIN_CONFIG_PATH:-/app/deploy/chain-config.json}"
      NPM_CONFIG_CACHE: /npm-cache
    command: >
      sh -lc "npm ci &&
              npx hardhat run scripts/deploy-local.ts --network docker &&
              npm run abi:export && npm run export:deployment"

  ipfs:
    extends:
      file: ./contracts/docker/compose.dev.yml
      service: ipfs
    networks: [ dfsp ]
    ports:
      - "${IPFS_API_HOST_PORT:-5001}:5001"
      - "${IPFS_GATEWAY_HOST_PORT:-8080}:8080"
    volumes:
      - ipfs:/data/ipfs

networks:
  dfsp:
    driver: bridge

volumes:
  pgdata: {}
  ipfs: {}
  shared: {}
  web_pnpm_store: {}
  contracts_npm_cache: {}
  web_app: {}
  contracts_app: {}

