# docker-compose.yml
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dfsp
      POSTGRES_PASSWORD: dfsp
      POSTGRES_DB: dfsp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./backend          # Dockerfile рядом (в backend/)
    env_file:
      - ./backend/.env
    environment:
      PYTHONPATH: /app
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  pgdata: {}
