/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { DFSPAnchoring, DFSPAnchoringInterface } from "../DFSPAnchoring.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "root",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "uint64",
        "name": "periodId",
        "type": "uint64"
      }
    ],
    "name": "Anchored",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "previousOwner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "OwnershipTransferred",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "root",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "periodId",
        "type": "uint64"
      }
    ],
    "name": "anchorMerkleRoot",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "renounceOwnership",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "transferOwnership",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b5060405161038338038061038383398101604081905261002e91610095565b61003733610046565b61004081610046565b506100c2565b5f80546001600160a01b038381166001600160a01b0319831681178455604051919092169283917f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e09190a35050565b5f602082840312156100a5575f80fd5b81516001600160a01b03811681146100bb575f80fd5b9392505050565b6102b4806100cf5f395ff3fe608060405234801561000f575f80fd5b506004361061004a575f3560e01c806330b16e3f1461004e578063715018a6146100635780638da5cb5b1461006b578063f2fde38b14610089575b5f80fd5b61006161005c366004610217565b61009c565b005b6100616100de565b5f54604080516001600160a01b039092168252519081900360200190f35b610061610097366004610251565b6100f1565b6100a461016f565b60405167ffffffffffffffff82169083907f41c3f410f5c8ac36bb46b1dccef0de0f964087c9e688795fa02ecfa2c20b3fe4905f90a35050565b6100e661016f565b6100ef5f6101c8565b565b6100f961016f565b6001600160a01b0381166101635760405162461bcd60e51b815260206004820152602660248201527f4f776e61626c653a206e6577206f776e657220697320746865207a65726f206160448201526564647265737360d01b60648201526084015b60405180910390fd5b61016c816101c8565b50565b5f546001600160a01b031633146100ef5760405162461bcd60e51b815260206004820181905260248201527f4f776e61626c653a2063616c6c6572206973206e6f7420746865206f776e6572604482015260640161015a565b5f80546001600160a01b038381166001600160a01b0319831681178455604051919092169283917f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e09190a35050565b5f8060408385031215610228575f80fd5b82359150602083013567ffffffffffffffff81168114610246575f80fd5b809150509250929050565b5f60208284031215610261575f80fd5b81356001600160a01b0381168114610277575f80fd5b939250505056fea2646970667358221220a1296d281185645d09292715ee6be0647ea4e66ab5561011b9d0771a28f7cc0964736f6c63430008180033";

  
      type DFSPAnchoringConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: DFSPAnchoringConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class DFSPAnchoring__factory extends ContractFactory {
    
      constructor(...args: DFSPAnchoringConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(owner_: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(owner_, overrides || {});
    };
    override deploy(owner_: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(owner_, overrides || {}) as Promise<DFSPAnchoring & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): DFSPAnchoring__factory {
      return super.connect(runner) as DFSPAnchoring__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): DFSPAnchoringInterface {
      return new Interface(_abi) as DFSPAnchoringInterface;
    }
    
    override attach(address: string | Addressable): DFSPAnchoring {
      return super.attach(address) as DFSPAnchoring;
    }
  static connect(address: string, runner?: ContractRunner | null): DFSPAnchoring {
      return new Contract(address, _abi, runner) as unknown as DFSPAnchoring;
    }
  }

  
  