"""create telegram_links and action_intents tables

Revision ID: <ID_ИЗ_ВАШЕГО_ФАЙЛА>
Revises: 850f302dfa93
Create Date: <ДАТА_ИЗ_ВАШЕГО_ФАЙЛА>

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
# ВАЖНО: Замените эти две строки на те, что сгенерировал Alembic в вашем файле
revision: str = '090cff9666f1'
down_revision: Union[str, None] = '850f302dfa93' # Предыдущая миграция
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Создаем таблицу action_intents
    op.create_table('action_intents',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('owner_address', sa.TEXT(), nullable=False),
        sa.Column('type', sa.TEXT(), nullable=False),
        sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('used_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_action_intents'))
    )
    # Создаем индекс для action_intents
    op.create_index(op.f('ix_action_intents_owner_address'), 'action_intents', ['owner_address'], unique=False)

    # Создаем таблицу telegram_links
    op.create_table('telegram_links',
        sa.Column('chat_id', sa.BIGINT(), nullable=False),
        sa.Column('wallet_address', sa.TEXT(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.PrimaryKeyConstraint('chat_id', 'wallet_address', name=op.f('pk_telegram_links'))
    )
    # Создаем частичный индекс для telegram_links
    op.create_index(
        'ix_tg_links_wallet_address',
        'telegram_links',
        ['wallet_address'],
        unique=False,
        postgresql_where=sa.text('revoked_at IS NULL')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Выполняем действия в обратном порядке

    # Удаляем индекс и таблицу telegram_links
    op.drop_index('ix_tg_links_wallet_address', table_name='telegram_links', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('telegram_links')

    # Удаляем индекс и таблицу action_intents
    op.drop_index(op.f('ix_action_intents_owner_address'), table_name='action_intents')
    op.drop_table('action_intents')

    # ### end Alembic commands ###