"""auto 20251022215338

Revision ID: 850f302dfa93
Revises: be38a1b2c3d4
Create Date: 2025-10-22 21:53:45.603771

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '850f302dfa93'
down_revision: Union[str, None] = 'be38a1b2c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ШАГ 1: СНАЧАЛА исправляем тип колонки events.file_id с UUID на BYTEA
    op.alter_column(
        "events",
        "file_id",
        existing_type=sa.UUID(),
        type_=sa.LargeBinary(length=32),
        postgresql_using="decode(replace(file_id::text, '-', ''), 'hex')",
    )

    # ШАГ 2: ТЕПЕРЬ создаем внешний ключ. Теперь типы совпадают.
    op.create_foreign_key(None, "events", "files", ["file_id"], ["id"], ondelete="SET NULL")

    # Остальные команды из оригинальной миграции
    op.alter_column(
        "file_versions",
        "size",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "file_versions", "mime", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
    )
    op.alter_column(
        "files", "name", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    op.alter_column(
        "files", "size", existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=False
    )
    op.alter_column(
        "files", "mime", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
    )
    op.alter_column(
        "files", "cid", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    op.create_index(op.f("ix_files_owner_id"), "files", ["owner_id"], unique=False)
    op.create_index(op.f("ix_grants_file_id"), "grants", ["file_id"], unique=False)
    op.create_index(op.f("ix_grants_grantee_id"), "grants", ["grantee_id"], unique=False)
    op.create_index(op.f("ix_grants_grantor_id"), "grants", ["grantor_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Для downgrade делаем все в обратном порядке

    # ШАГ 1: СНАЧАЛА удаляем внешний ключ
    # Имя констрейнта нужно будет уточнить, если Alembic не сможет его найти
    op.drop_constraint("events_file_id_fkey", "events", type_="foreignkey")

    # ШАГ 2: ТЕПЕРЬ возвращаем тип колонки к UUID
    op.alter_column(
        "events",
        "file_id",
        existing_type=sa.LargeBinary(length=32),
        type_=sa.UUID(),
        postgresql_using="encode(file_id, 'hex')::uuid",
    )

    # Остальные команды из оригинальной миграции (в обратном порядке)
    op.drop_index(op.f("ix_grants_grantor_id"), table_name="grants")
    op.drop_index(op.f("ix_grants_grantee_id"), table_name="grants")
    op.drop_index(op.f("ix_grants_file_id"), table_name="grants")
    op.drop_index(op.f("ix_files_owner_id"), table_name="files")
    op.alter_column(
        "files", "cid", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    op.alter_column(
        "files", "mime", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
    )
    op.alter_column(
        "files", "size", existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=False
    )
    op.alter_column(
        "files", "name", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    op.alter_column(
        "file_versions", "mime", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
    )
    op.alter_column(
        "file_versions",
        "size",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.alter_column(
        "file_versions", "cid", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    # ### end Alembic commands ###
