"""auto 20251007043639

Revision ID: 9202fdda749d
Revises: 12568120f3dc
Create Date: 2025-10-07 04:36:45.894708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9202fdda749d'
down_revision: Union[str, None] = '12568120f3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id_hex', sa.String(length=66), nullable=False),
    sa.Column('cid', sa.String(length=120), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('owner', sa.String(length=42), nullable=True),
    sa.Column('chain_block', sa.Integer(), nullable=True),
    sa.Column('chain_timestamp', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_chain_block'), 'assets', ['chain_block'], unique=False)
    op.create_index(op.f('ix_assets_cid'), 'assets', ['cid'], unique=False)
    op.create_index(op.f('ix_assets_file_id_hex'), 'assets', ['file_id_hex'], unique=False)
    op.create_index(op.f('ix_assets_owner'), 'assets', ['owner'], unique=False)
    op.create_index(op.f('ix_assets_tx_hash'), 'assets', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_tx_hash'), table_name='assets')
    op.drop_index(op.f('ix_assets_owner'), table_name='assets')
    op.drop_index(op.f('ix_assets_file_id_hex'), table_name='assets')
    op.drop_index(op.f('ix_assets_cid'), table_name='assets')
    op.drop_index(op.f('ix_assets_chain_block'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
