"""auto 20251012225827

Revision ID: d62c645073b8
Revises: 68057369ab53
Create Date: 2025-10-12 22:58:33.724456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd62c645073b8'
down_revision: Union[str, None] = '68057369ab53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_versions', 'size')
    op.drop_column('file_versions', 'mime')
    op.drop_column('file_versions', 'checksum')
    op.drop_constraint('uq_files_bytes32_id', 'files', type_='unique')
    op.drop_column('files', 'bytes32_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('bytes32_id', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_files_bytes32_id', 'files', ['bytes32_id'], postgresql_nulls_not_distinct=False)
    op.add_column('file_versions', sa.Column('checksum', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.add_column('file_versions', sa.Column('mime', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('file_versions', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
