/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AccessControlDFSP {
  export type GrantStruct = {
    grantor: AddressLike;
    grantee: AddressLike;
    fileId: BytesLike;
    expiresAt: BigNumberish;
    maxDownloads: BigNumberish;
    used: BigNumberish;
    createdAt: BigNumberish;
    revoked: boolean;
  };

  export type GrantStructOutput = [
    grantor: string,
    grantee: string,
    fileId: string,
    expiresAt: bigint,
    maxDownloads: bigint,
    used: bigint,
    createdAt: bigint,
    revoked: boolean
  ] & {
    grantor: string;
    grantee: string;
    fileId: string;
    expiresAt: bigint;
    maxDownloads: bigint;
    used: bigint;
    createdAt: bigint;
    revoked: boolean;
  };
}

export interface AccessControlDFSPInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canDownload"
      | "grant"
      | "grantBearer"
      | "grantNonces"
      | "grantOf"
      | "grants"
      | "isTrustedForwarder"
      | "revoke"
      | "useOnce"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Granted" | "Revoked" | "Used"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canDownload",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grant",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantBearer",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantNonces",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "grantOf", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "grants", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "revoke", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "useOnce", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "canDownload",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grant", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantBearer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grants", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "useOnce", data: BytesLike): Result;
}

export namespace GrantedEvent {
  export type InputTuple = [
    capId: BytesLike,
    grantor: AddressLike,
    grantee: AddressLike,
    fileId: BytesLike,
    expiresAt: BigNumberish,
    maxDownloads: BigNumberish
  ];
  export type OutputTuple = [
    capId: string,
    grantor: string,
    grantee: string,
    fileId: string,
    expiresAt: bigint,
    maxDownloads: bigint
  ];
  export interface OutputObject {
    capId: string;
    grantor: string;
    grantee: string;
    fileId: string;
    expiresAt: bigint;
    maxDownloads: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevokedEvent {
  export type InputTuple = [capId: BytesLike, grantor: AddressLike];
  export type OutputTuple = [capId: string, grantor: string];
  export interface OutputObject {
    capId: string;
    grantor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsedEvent {
  export type InputTuple = [capId: BytesLike, used: BigNumberish];
  export type OutputTuple = [capId: string, used: bigint];
  export interface OutputObject {
    capId: string;
    used: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AccessControlDFSP extends BaseContract {
  connect(runner?: ContractRunner | null): AccessControlDFSP;
  waitForDeployment(): Promise<this>;

  interface: AccessControlDFSPInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canDownload: TypedContractMethod<
    [user: AddressLike, fileId: BytesLike],
    [boolean],
    "view"
  >;

  grant: TypedContractMethod<
    [
      fileId: BytesLike,
      grantee: AddressLike,
      ttlSec: BigNumberish,
      maxDownloads: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  grantBearer: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish, arg2: BigNumberish],
    [string],
    "view"
  >;

  grantNonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  grantOf: TypedContractMethod<
    [capId: BytesLike],
    [AccessControlDFSP.GrantStructOutput],
    "view"
  >;

  grants: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint, boolean] & {
        grantor: string;
        grantee: string;
        fileId: string;
        expiresAt: bigint;
        maxDownloads: bigint;
        used: bigint;
        createdAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  isTrustedForwarder: TypedContractMethod<
    [forwarder: AddressLike],
    [boolean],
    "view"
  >;

  revoke: TypedContractMethod<[capId: BytesLike], [void], "nonpayable">;

  useOnce: TypedContractMethod<[capId: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canDownload"
  ): TypedContractMethod<
    [user: AddressLike, fileId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "grant"
  ): TypedContractMethod<
    [
      fileId: BytesLike,
      grantee: AddressLike,
      ttlSec: BigNumberish,
      maxDownloads: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantBearer"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish, arg2: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantNonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantOf"
  ): TypedContractMethod<
    [capId: BytesLike],
    [AccessControlDFSP.GrantStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grants"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint, boolean] & {
        grantor: string;
        grantee: string;
        fileId: string;
        expiresAt: bigint;
        maxDownloads: bigint;
        used: bigint;
        createdAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTrustedForwarder"
  ): TypedContractMethod<[forwarder: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<[capId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "useOnce"
  ): TypedContractMethod<[capId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "Granted"
  ): TypedContractEvent<
    GrantedEvent.InputTuple,
    GrantedEvent.OutputTuple,
    GrantedEvent.OutputObject
  >;
  getEvent(
    key: "Revoked"
  ): TypedContractEvent<
    RevokedEvent.InputTuple,
    RevokedEvent.OutputTuple,
    RevokedEvent.OutputObject
  >;
  getEvent(
    key: "Used"
  ): TypedContractEvent<
    UsedEvent.InputTuple,
    UsedEvent.OutputTuple,
    UsedEvent.OutputObject
  >;

  filters: {
    "Granted(bytes32,address,address,bytes32,uint64,uint32)": TypedContractEvent<
      GrantedEvent.InputTuple,
      GrantedEvent.OutputTuple,
      GrantedEvent.OutputObject
    >;
    Granted: TypedContractEvent<
      GrantedEvent.InputTuple,
      GrantedEvent.OutputTuple,
      GrantedEvent.OutputObject
    >;

    "Revoked(bytes32,address)": TypedContractEvent<
      RevokedEvent.InputTuple,
      RevokedEvent.OutputTuple,
      RevokedEvent.OutputObject
    >;
    Revoked: TypedContractEvent<
      RevokedEvent.InputTuple,
      RevokedEvent.OutputTuple,
      RevokedEvent.OutputObject
    >;

    "Used(bytes32,uint32)": TypedContractEvent<
      UsedEvent.InputTuple,
      UsedEvent.OutputTuple,
      UsedEvent.OutputObject
    >;
    Used: TypedContractEvent<
      UsedEvent.InputTuple,
      UsedEvent.OutputTuple,
      UsedEvent.OutputObject
    >;
  };
}
